---
- name: Set the hostname.
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"
  become: true

- name: Ensure hostname is in /etc/hosts
  blockinfile:
    dest: /etc/hosts
    block: >
      {{ ip }} {{ hostname }} {{ hostname_aliases | join(' ') }}
  vars:
    ip: >-
      {{ ansible_default_ipv4.address if hostname_ip|lower == 'auto' else hostname_ip }}
    hostname: >-
      {{ inventory_hostname if hostname_fqdn|lower == 'inventory' else hostname_fqdn }}
    aliases: >-
      {{ hostname_aliases | join(' ') }}
  when: hostname_inject_hosts_file
  become: true
