---
- name: Check if the system uses systemd.
  assert:
    that: ansible_service_mgr == 'systemd'
    fail_msg: "This role expects systemd."
    quiet: true

- name: Execute distribution dependent setup.
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"
    - generic.yml
