---
- name: Set role variables.
  ansible.builtin.set_fact:
    ip: >-
      {{ ansible_default_ipv4.address if hostname_ip|lower == 'auto' else hostname_ip }}
    hostname_long: >-
      {{ inventory_hostname if hostname_fqdn|lower == 'inventory' else hostname_fqdn }}
    hostname_short: >-
      {{ inventory_hostname_short if hostname_short|lower == 'inventory' else hostname_short }}
    aliases: >-
      {{ hostname_aliases | join(' ') }}

- name: Set the system hostname.
  ansible.builtin.hostname:
    name: "{{ hostname_short }}"
  become: true

- name: Ensure hostname is in system hostfile.
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    search_string: "127.0.1.1"
    line: "{{ ip }} {{ hostname_long }} {{ hostname_short }} {{ hostname_aliases | join(' ') }}"
  when: hostname_inject_hosts_file
  become: true
